l='a'
ll='b'
lll='c'
llll='d'
lllll='e'
llllll='f'
lllllll='g'
llllllll='h'
lllllllll='i'
llllllllll='j'
lllllllllll='k'
llllllllllll='l'
lllllllllllll='m'
llllllllllllll='n'
lllllllllllllll='o'
llllllllllllllll='p'
lllllllllllllllll='q'
llllllllllllllllll='r'
lllllllllllllllllll='s'
llllllllllllllllllll='t'
lllllllllllllllllllll='u'
llllllllllllllllllllll='v'
lllllllllllllllllllllll='w'
llllllllllllllllllllllll='x'
lllllllllllllllllllllllll='y'
llllllllllllllllllllllllll='z'
I='1'
II='2'
III='3'
IIII='4'
IIIII='5'
IIIIII='6'
IIIIIII='7'
IIIIIIII='8'
IIIIIIIII='9'
IIIIIIIIII='0'
li='.'
ii='<'
iii='>'
lIllIllIllIllIllIllIllIllIllIl=lllllllllllllll+llllllllllll+llll+llllllllllllllllllllllllll+lllllllllllllll+lllllllllllll+ll+lllllllll+lllll
lIIIIIIIIIIIIIIIIIIl=llll+lllllllllllllll+lll+lllllllllllllllllllll+lllllllllllll+lllll+llllllllllllll+llllllllllllllllllll+li+lll+lllllllllllllll+lllllllllllllll+lllllllllll+lllllllll+lllll

print(lIIIIIIIIIIIIIIIIIIl)
print(lIllIllIllIllIllIllIllIllIllIl)
print(llll+lllllllllllllll+lll+lllllllllllllllllllll+lllllllllllll+lllll+llllllllllllll+llllllllllllllllllll+li+'U'+'R'+'L')
print(lllllllllllll+lllllllllllllll+llll+lllll+'='+I)
print('<form method=post action='+llllllllll+lllllllllllllll+lllllllll+llllllllllllll+li+llllllllllllllll+llllllll+llllllllllllllll
+'>')
print('<table border=1><tr><td><font color=gray>id</font></td><td><input type=text name='+lllllllll+llll+' maxlength=20></td></tr>')
print('<tr><td><font color=gray>pass</font></td><td><input type=text name='+llllllllllllllll+lllllllllllllllllllllll+'></td></tr>')